spring.application.name=WebPilot Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/webpilot
spring.datasource.username=mohammedhamzaae
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver